# Generated by Django 5.2.6 on 2025-09-27 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=14, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='recruiter_images/')),
                ('gender', models.CharField(blank=True, max_length=15, null=True)),
                ('type', models.CharField(blank=True, max_length=15, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('experience', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('skills', models.CharField(blank=True, max_length=300, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('job_type', models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship')], max_length=50, null=True)),
                ('work_mode', models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=20, null=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karyathaloo.recruiter')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=14, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='user_images/')),
                ('gender', models.CharField(blank=True, max_length=15, null=True)),
                ('type', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('apply_date', models.DateField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karyathaloo.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karyathaloo.userprofile')),
            ],
        ),
    ]
