# Generated by Django 5.2.6 on 2025-09-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karyathaloo', '0002_apply_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
