# Generated by Django 5.2.6 on 2025-10-29 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karyathaloo', '0005_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
