# Generated by Django 5.2.6 on 2025-11-16 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karyathaloo', '0006_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payout_status', models.CharField(choices=[('PENDING', 'Payment Pending'), ('INITIATED', 'Payment Initiated'), ('COMPLETED', 'Payment Completed'), ('FAILED', 'Payment Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(help_text="Payout is only created for 'Accepted' applications.", limit_choices_to={'status': 'Accepted'}, on_delete=django.db.models.deletion.CASCADE, to='karyathaloo.apply')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karyathaloo.recruiter')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karyathaloo.userprofile')),
            ],
        ),
    ]
