# Generated by Django 5.2.6 on 2025-11-16 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karyathaloo', '0007_recruiterpayout'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('gateway_name', models.CharField(default='Internal Ledger', max_length=50)),
                ('transaction_status', models.CharField(choices=[('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karyathaloo.recruiterpayout')),
            ],
        ),
    ]
